/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * Vault REST API - version 2.0.12
 *
 * The Vault REST API provides access to the Vault database, offering a set of endpoints divided into two main sections: Global and Vault. The Global section includes general operations applicable across the system, while the Vault section specifically handles interactions with the Vault data. It&#x27;s designed to provide a seamless interface for users to interact with their Vaulted data.
 *
 * OpenAPI version: 3.0.1
 *
 * Contact:
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'global.getApiSpec': ['GET', '/openapi-spec.yml'],
  'global.getServerInfo': ['GET', '/server-info'],
  'global.getGroups': ['GET', '/groups'],
  'global.getGroupById': ['GET', '/groups/{id}'],
  'global.getAccountByAuthType': ['GET', '/groups/{id}/accounts/{authType}'],
  'global.getProfileAttributeDefinitions': ['GET', '/profile-attribute-definitions'],
  'global.getProfileAttributeDefinitionById': ['GET', '/profile-attribute-definitions/{id}'],
  'global.getRoles': ['GET', '/roles'],
  'global.getRoleById': ['GET', '/roles/{id}'],
  'global.createSession': ['POST', '/sessions'],
  'global.createSessionWithWinAuth': ['POST', '/sessions/win-auth'],
  'global.getSessionById': ['GET', '/sessions/{id}'],
  'global.deleteSession': ['DELETE', '/sessions/{id}'],
  'global.getSystemOptions': ['GET', '/system-options'],
  'global.createSystemOption': ['POST', '/system-options'],
  'global.getSystemOptionById': ['GET', '/system-options/{id}'],
  'global.updateSystemOptionById': ['PATCH', '/system-options/{id}'],
  'global.deleteSystemOptionById': ['DELETE', '/system-options/{id}'],
  'global.getAllUsers': ['GET', '/users'],
  'global.getUserById': ['GET', '/users/{id}'],
  'global.getUserAccounts': ['GET', '/users/{id}/accounts'],
  'global.getUsersAccountByAuthType': ['GET', '/users/{id}/accounts/{authType}'],
  'global.getVaults': ['GET', '/vaults'],
  'global.getVaultById': ['GET', '/vaults/{id}'],
  'vault.getChangeOrders': ['GET', '/vaults/{vaultId}/change-orders'],
  'vault.getChangeOrderById': ['GET', '/vaults/{vaultId}/change-orders/{id}'],
  'vault.getChangeOrderRelatedFiles': ['GET', '/vaults/{vaultId}/change-orders/{id}/all-related-files'],
  'vault.getChangeOrderAssociatedEntities': ['GET', '/vaults/{vaultId}/change-orders/{id}/associated-entities'],
  'vault.getChangeOrderComments': ['GET', '/vaults/{vaultId}/change-orders/{id}/comments'],
  'vault.getChangeOrderCommentAttachments': ['GET', '/vaults/{vaultId}/eco-comments/{id}/attachments'],
  'vault.getFileVersions': ['GET', '/vaults/{vaultId}/file-versions'],
  'vault.getFileVersionById': ['GET', '/vaults/{vaultId}/file-versions/{id}'],
  'vault.getFileVersionSignedUrl': ['GET', '/vaults/{vaultId}/file-versions/{id}/signedurl'],
  'vault.getFileVersionContent': ['GET', '/vaults/{vaultId}/file-versions/{id}/content'],
  'vault.getFileVersionContentHead': ['HEAD', '/vaults/{vaultId}/file-versions/{id}/content'],
  'vault.getFileVersionLmvRoot': ['GET', '/vaults/{vaultId}/file-versions/{id}/svf/bubble.json'],
  'vault.getFileVersionAssociatedItemVersions': ['GET', '/vaults/{vaultId}/file-versions/{id}/item-versions'],
  'vault.getFileVersionMarkups': ['GET', '/vaults/{vaultId}/file-versions/{id}/markups'],
  'vault.getFileVersionMarkupById': ['GET', '/vaults/{vaultId}/file-versions/{id}/markups/{markupId}'],
  'vault.getFileVersionThumbnailById': ['GET', '/vaults/{vaultId}/file-versions/{id}/thumbnail'],
  'vault.getFileVersionVisualizationAttachment': [
    'GET',
    '/vaults/{vaultId}/file-versions/{id}/visualization-attachment'
  ],
  'vault.getFileVersionUses': ['GET', '/vaults/{vaultId}/file-versions/{id}/uses'],
  'vault.getFileVersionWhereUsed': ['GET', '/vaults/{vaultId}/file-versions/{id}/parents'],
  'vault.getFileById': ['GET', '/vaults/{vaultId}/files/{id}'],
  'vault.getFileAssociatedChangeOrders': ['GET', '/vaults/{vaultId}/files/{id}/change-orders'],
  'vault.getFileHistory': ['GET', '/vaults/{vaultId}/files/{id}/versions'],
  'vault.getFolderById': ['GET', '/vaults/{vaultId}/folders/{id}'],
  'vault.getFolderContents': ['GET', '/vaults/{vaultId}/folders/{id}/contents'],
  'vault.getFolderSubFolders': ['GET', '/vaults/{vaultId}/folders/{id}/sub-folders'],
  'vault.getItemVersions': ['GET', '/vaults/{vaultId}/item-versions'],
  'vault.getItemVersionById': ['GET', '/vaults/{vaultId}/item-versions/{id}'],
  'vault.getItemVersionAssociatedFiles': ['GET', '/vaults/{vaultId}/item-versions/{id}/associated-files'],
  'vault.getItemVersionBom': ['GET', '/vaults/{vaultId}/item-versions/{id}/bill-of-materials'],
  'vault.getItemVersionWhereUsed': ['GET', '/vaults/{vaultId}/item-versions/{id}/parents'],
  'vault.getItemVersionThumbnail': ['GET', '/vaults/{vaultId}/item-versions/{id}/thumbnail'],
  'vault.getItems': ['GET', '/vaults/{vaultId}/items'],
  'vault.getItemById': ['GET', '/vaults/{vaultId}/items/{id}'],
  'vault.getItemAssociatedChangeOrders': ['GET', '/vaults/{vaultId}/items/{id}/change-orders'],
  'vault.getItemHistory': ['GET', '/vaults/{vaultId}/items/{id}/versions'],
  'vault.addJob': ['POST', '/vaults/{vaultId}/jobs'],
  'vault.getJobQueueEnabled': ['GET', '/vaults/{vaultId}/jobs/job-queue-enabled'],
  'vault.getJobsById': ['GET', '/vaults/{vaultId}/jobs/{id}'],
  'vault.getLinks': ['GET', '/vaults/{vaultId}/links'],
  'vault.getLinkById': ['GET', '/vaults/{vaultId}/links/{id}'],
  'vault.getPropertyDefinitions': ['GET', '/vaults/{vaultId}/property-definitions'],
  'vault.getPropertyDefinitionById': ['GET', '/vaults/{vaultId}/property-definitions/{id}'],
  'vault.search': ['GET', '/vaults/{vaultId}/search-results'],
  'vault.advancedSearch': ['POST', '/vaults/{vaultId}:advanced-search'],
  'vault.getVaultOptions': ['GET', '/vaults/{vaultId}/vault-options'],
  'vault.createVaultOption': ['POST', '/vaults/{vaultId}/vault-options'],
  'vault.getVaultOptionById': ['GET', '/vaults/{vaultId}/vault-options/{id}'],
  'vault.updateVaultOptionById': ['PATCH', '/vaults/{vaultId}/vault-options/{id}'],
  'vault.deleteVaultOptionById': ['DELETE', '/vaults/{vaultId}/vault-options/{id}']
};
